name: kakao_flutter_sdk
description: A flutter plugin for Kakao API, which supports Kakao login, KakaoTalk Share, User API, KakaoTalk API, KakaoStory API and Navi API.
version: 1.4.2
homepage: https://github.com/kakao/kakao_flutter_sdk
issue_tracker: https://github.com/kakao/kakao_flutter_sdk/issues

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: '>=2.0.0'

platforms:
  android:
  ios:
  web:

dependencies:
  flutter:
    sdk: flutter
  kakao_flutter_sdk_common:
    git:
      url: https://github.com/nm-eido9oya/kakao_flutter_sdk.git
      ref: develop
      path: packages/kakao_flutter_sdk_common
  kakao_flutter_sdk_auth:
    git:
      url: https://github.com/nm-eido9oya/kakao_flutter_sdk.git
      ref: develop
      path: packages/kakao_flutter_sdk_auth
  kakao_flutter_sdk_share:
    git:
      url: https://github.com/nm-eido9oya/kakao_flutter_sdk.git
      ref: develop
      path: packages/kakao_flutter_sdk_share
  kakao_flutter_sdk_navi:
    git:
      url: https://github.com/nm-eido9oya/kakao_flutter_sdk.git
      ref: develop
      path: packages/kakao_flutter_sdk_navi
  kakao_flutter_sdk_story:
    git:
      url: https://github.com/nm-eido9oya/kakao_flutter_sdk.git
      ref: develop
      path: packages/kakao_flutter_sdk_story
  kakao_flutter_sdk_talk:
    git:
      url: https://github.com/nm-eido9oya/kakao_flutter_sdk.git
      ref: develop
      path: packages/kakao_flutter_sdk_talk
  kakao_flutter_sdk_template:
    git:
      url: https://github.com/nm-eido9oya/kakao_flutter_sdk.git
      ref: develop
      path: packages/kakao_flutter_sdk_template
  kakao_flutter_sdk_user:
    git:
      url: https://github.com/nm-eido9oya/kakao_flutter_sdk.git
      ref: develop
      path: packages/kakao_flutter_sdk_user
  kakao_flutter_sdk_friend:
    git:
      url: https://github.com/nm-eido9oya/kakao_flutter_sdk.git
      ref: develop
      path: packages/kakao_flutter_sdk_friend

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
